### ISSUE TITLE
关于通过 getFlutterShellArgs() 来实现热更

### ISSUE THREAD

**Issue by siyehua** [llew2011/flutter_hotfix#2]
楼主你提到的两种方案:

1. 文件不存在
2. 文件名错误

如果是一个已经发出去的 apk, 那:

1. 就无法实现了,默认是存在的
2. 文件名错误, 你是通过配置 Mainfest 来修改的, 问题是 Mainfest 也已经下发了..

所以我感觉这两个方案都不行吧

**Comment by llew2011** [comment]
改下文件名





------------------ 原始邮件 ------------------
发件人: siyehua <notifications@github.com&gt;
发送时间: 2021年3月1日 15:50
收件人: llew2011/flutter_hotfix <flutter_hotfix@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[llew2011/flutter_hotfix] 关于通过 getFlutterShellArgs() 来实现热更 (#2)





 
楼主你提到的两种方案:
  
文件不存在 

文件名错误 
 
如果是一个已经发出去的 apk, 那:
  
就无法实现了,默认是存在的 

文件名错误, 你是通过配置 Mainfest 来修改的, 问题是 Mainfest 也已经下发了.. 
 
所以我感觉这两个方案都不行吧

**Comment by siyehua** [comment]
> 改下文件名
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: siyehua <notifications@github.com&gt; 发送时间: 2021年3月1日 15:50 收件人: llew2011/flutter_hotfix <flutter_hotfix@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[llew2011/flutter_hotfix] 关于通过 getFlutterShellArgs() 来实现热更 (#2) 楼主你提到的两种方案: 文件不存在 文件名错误 如果是一个已经发出去的 apk, 那: 就无法实现了,默认是存在的 文件名错误, 你是通过配置 Mainfest 来修改的, 问题是 Mainfest 也已经下发了.. 所以我感觉这两个方案都不行吧 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

改文件名要你第一版就改了, 就是你刚开始发布出去的就已经在 Mainfest 中写了一个错误的, 如果已经发布出去的,就没法改 Mainfest 了

**Comment by llew2011** [comment]
你第一版发出去的假设是A文件，但是你可以在第二版引擎启动前把A改了哇，这样你的第二版A不就是不存在了么




------------------ 原始邮件 ------------------
发件人: siyehua <notifications@github.com&gt;
发送时间: 2021年3月2日 10:17
收件人: llew2011/flutter_hotfix <flutter_hotfix@noreply.github.com&gt;
抄送: llew2011 <337876594@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[llew2011/flutter_hotfix] 关于通过 getFlutterShellArgs() 来实现热更 (#2)





  
改下文件名
 …
 ------------------ 原始邮件 ------------------ 发件人: siyehua <notifications@github.com&gt; 发送时间: 2021年3月1日 15:50 收件人: llew2011/flutter_hotfix <flutter_hotfix@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[llew2011/flutter_hotfix] 关于通过 getFlutterShellArgs() 来实现热更 (#2) 楼主你提到的两种方案: 文件不存在 文件名错误 如果是一个已经发出去的 apk, 那: 就无法实现了,默认是存在的 文件名错误, 你是通过配置 Mainfest 来修改的, 问题是 Mainfest 也已经下发了.. 所以我感觉这两个方案都不行吧 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
改文件名要你第一版就改了, 就是你刚开始发布出去的就已经在 Mainfest 中写了一个错误的, 如果已经发布出去的,就没法改 Mainfest 了

**Comment by llew2011** [comment]
另外有看了下代码，其实直接添加你自己的so路径就好了，它的优先级是最高的，引擎会优先加载你自己的so
